title: Rob Storm
email: the1wolfcast@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gameplay Programmer
baseurl: "/Portfolio/" # the subpath of your site, e.g. /blog
url: "https://rob-storm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  Rob-Storm

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  guides:
    output: true
    permalink: /guides/:name/
  articles:
    output: true
    permalink: /articles/:name/

# Syntax highlighting
markdown: kramdown

kramdown: 
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1